approve_by_comment: true
approve_regex: '^(:\+1:|:shipit:|Approved|OK)|LGTM'
reject_regex: '^(:-1:|Rejected)'
# reject_value: -1
reset_on_push: true
reset_on_reopened: true
# author_approval: ignored
reviewers:
    - # maintainer has to approve everything that is _merged to master_
        name: maintainer
        required: 1
        members:
            - laughedelic
        conditions:
            branches:
                - master
    - # anybody from the repo collaborators needs to review a PR _with the label_
        name: collaborators
        required: 1
        members: all
        conditions:
            labels:
                - needs-review
    - # all developers have to review PRs _merged to master_, _with the label_ and _changed sources_
        name: developers
        required: -1
        members:
            - laughedelic
            - eparejatobes
        conditions:
            labels:
                - needs-review
            files:
                - "*.scala"
            branches:
                - master
